version: "3"

services: 

    mysql:
        image: mysql:5.7
        container_name: mysql
        volumes: 
            - "./mysql/database.sql:/docker-entrypoint-initdb.d/database.sql"
            - "dbdata:/var/lib/mysql"
        environment: 
            - MYSQL_ROOT_PASSWORD=root
        networks: 
            - backend

    app:
        build:
            context: app
        image: app
        entrypoint: dockerize -wait tcp://mysql:3306 -timeout 20s python -m flask run --host=0.0.0.0
        container_name: app
        environment: 
            - DB_DATABASE=desafio
            - DB_HOST=mysql
            - DB_USER=root
            - DB_PASSWD=root
        depends_on: 
            - mysql
        networks: 
            - backend
            - frontend

    nginx:
        build: 
            context: nginx
        image: nginx
        container_name: nginx
        ports: 
            - "8000:80"
        depends_on: 
            - app
        networks: 
            - frontend
        restart: always

volumes: 
    dbdata:

networks: 
    backend:
    frontend:
    
